# Generated by Django 5.2.5 on 2025-10-08 16:18

import LunitTuneApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('genreid', models.CharField(blank=True, max_length=64)),
                ('playsnum', models.IntegerField(default=0)),
                ('adult', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=LunitTuneApp.models.audio_upload_to)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=LunitTuneApp.models.cover_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('genreid', models.CharField(blank=True, max_length=64)),
                ('playsnum', models.IntegerField(default=0)),
                ('adult', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=LunitTuneApp.models.audio_upload_to)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=LunitTuneApp.models.cover_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('artistid', models.CharField(max_length=100, null=True)),
                ('genreid', models.CharField(blank=True, max_length=100, null=True)),
                ('albumid', models.CharField(blank=True, max_length=100, null=True)),
                ('playsnum', models.CharField(default='0', max_length=100)),
                ('adult', models.BooleanField(default=False)),
                ('time', models.FloatField(default=0.0)),
                ('audio', models.FileField(blank=True, null=True, upload_to='tracks/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrator')),
                ('is_client', models.BooleanField(default=False, verbose_name='Client')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='playlist_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='LunitTuneApp.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunitTuneApp.track')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'track')},
            },
        ),
    ]
