# Generated by Django 5.2.5 on 2025-10-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunitTuneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artistid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ArtistLinks',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('listeners', models.CharField(blank=True, default='0', max_length=32)),
                ('playlist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist', to='LunitTuneApp.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='audiobook',
            name='author_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiobooks', to='LunitTuneApp.artistlinks'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='host_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='LunitTuneApp.artistlinks'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='LunitTuneApp.artistlinks'),
        ),
    ]
