# Generated by Django 5.2.5 on 2025-10-23 12:13

import LunitTuneApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunitTuneApp', '0002_alter_track_artistid_artistlinks_audiobook_author_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[LunitTuneApp.models.validate_min_age])),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('role', models.CharField(choices=[('user', 'Звичайний користувач'), ('author', 'Автор пісень')], default='user', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
